### ISSUE TITLE
Shall we disable offline mode in mock?

### ISSUE THREAD

**Issue by siteshwar** [openscanhub/fedora-infra#69]
Currently offline mode is enabled in mock and it is causing [build failures](https://openscanhub.fedoraproject.org/task/4457/log/stdout.log). This package was built [successfully](https://download.copr.fedorainfracloud.org/results/packit/containers-aardvark-dns-439/fedora-rawhide-x86_64/07897352-aardvark-dns/builder-live.log.gz) in Copr. This issue tracks if we should disable offline mode in OpenScanHub too.

**Comment by kdudka** [comment]
Sounds like a good idea to me.  OpenScanHub does not produce any packages that users would run, so the risk associated with this configuration is lower compared to build services etc.

**Comment by siteshwar** [comment]
This issue was discussed during GNU Tools Cauldron 2024 with @davidmalcolm and @codonell. If we agree to disable offline mode, then it should be done in a safe manner.

**Comment by codonell** [comment]
@siteshwar @kdudka Speaking from first principles we should never disable offline mode. Why is online mode needed? What is the actual problem? All of our builds from upstream, down through to downstream should be done offline after dependency resolution is complete. Any requirement to be online is technically a defect in isolation? Is it because the scanning tool running in mock needs to call home for some reason? Is it a license check? Is it to download something? Whatever it is, it poses a problem since it exposes the rest of the pipeline to being online and that may trigger the pipeline to do something different e.g. "Oh I'm online, I'll update my local copy." etc. when it wouldn't otherwise do that. Therefore we might not be testing what we thing we're testing anymore.

This should not be done lightly.

**Comment by kdudka** [comment]
The scanners used by https://openscanhub.fedoraproject.org/ do not need Internet access.  So it is mostly about the source RPM packages themselves.  If they can be built in the offline mode with the provided mock configuration, OSH should be able to scan them fully automatically.  Enabling the Internet access was proposed as a workaround for some (testing) packages that cannot be rebuilt in up2date buildroot without Internet access.  Nevertheless, as you say, it is probably not worth the troubles.

**Comment by siteshwar** [comment]
I am closing this issue as we would like to avoid enabling online mode due to security concerns.
